# Generated by Django 2.0.6 on 2018-06-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotMetal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('castNo', models.CharField(max_length=10)),
                ('tlcNo', models.IntegerField(max_length=3)),
                ('silicon', models.DecimalField(decimal_places=2, max_digits=3)),
                ('sulphur', models.DecimalField(decimal_places=3, max_digits=4)),
                ('manganese', models.DecimalField(decimal_places=3, max_digits=4)),
                ('phosphorus', models.DecimalField(decimal_places=3, max_digits=4)),
                ('hmTemperature', models.IntegerField(max_length=4)),
                ('receiveTime', models.DateTimeField()),
                ('reportTime', models.DateTimeField()),
            ],
        ),
    ]
