# Generated by Django 2.0.6 on 2018-06-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotmetal',
            name='hmTemperature',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hotmetal',
            name='tlcNo',
            field=models.IntegerField(),
        ),
    ]
