# Generated by Django 2.0.6 on 2018-06-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bf', '0002_auto_20180630_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotmetal',
            name='receiveTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='hotmetal',
            name='reportTime',
            field=models.TimeField(),
        ),
    ]
